platform :ios, '12.0'

use_frameworks!

target 'EmptyTestApp' do
end

target 'CoJezdzi' do
  
end

target 'CoJezdziUITests' do
    inherit! :search_paths

    pod 'SBTUITestTunnel/Client'
    pod 'Overture'
end

target 'AppFramework' do
    pod 'Colours'
    pod 'HTTPStatusCodes'
    pod 'ReSwift'
    pod 'R.swift'
    pod 'Overture'
    pod 'SBTUITestTunnel/Server'
    pod 'GCDWebServer', :inhibit_warnings => true
end

target 'AppFrameworkTests' do
    pod 'Overture'
    pod 'ReSwift'
end

target 'TestsHelpper' do
    pod 'Overture'
    pod 'ReSwift'
end

# dsymys for all installed pods
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf-with-dsym'
        end
    end
end
